kubeslice/worker-operator

tests/hub/hub_suite_test.go, tests/hub/serviceimport_controller_test.go, tests/hub/slice_controller_test.go, tests/hub/slicegw_controller_test.go, tests/spoke/service_discovery_test.go, tests/spoke/spoke_suite_test.go
Added Test cases related to events and change spokev1alpha1 to workerv1alpha1
Signed-off-by: Rahul-D78 <rahul.kumar@aveshasystems.com>
=> test(AM-ITsForEvents): added ITs For Events

controllers/slicegateway/reconciler.go, internal/hub/controllers/mocks.go, internal/hub/controllers/slice_controller_unit_test.go
Signed-off-by: kon3m <aakash.dokka@aveshasystems.com>
=> added unit tests for slice controller

tests/spoke/slicegw_controller_test.go, tests/spoke/spoke_suite_test.go
Signed-off-by: Rahul-D78 <rahul.kumar@aveshasystems.com>
=> slicegw test cases added

controllers/slice/slicerouter.go, controllers/slicegateway/reconciler.go, tests/emulator/hubclient/hubclient.go, tests/spoke/slice_controller_test.go, tests/spoke/spoke_suite_test.go
test cases for 
* slice router reconciliation
* app pod list reconciliation
=> Slice reconciler tests

tests/spoke/service_discovery_test.go
Signed-off-by: Rahul-D78 <rahul.kumar@aveshasystems.com>
=> Fixed broken SvcEx IT

.github/workflows/build-test.yml, tests/hub/slice_controller_test.go, tests/hub/slicegw_controller_test.go, tests/spoke/slice_controller_test.go
Uses Eventually more and DeepEqual instead of direct comparison
Signed-off-by: gourishkb <104021126+gourishkb@users.noreply.github.com>
=> test(AM-fixingFlackyTests): Uses Eventually more and DeepEqual

README.md
Replaced the doc links with the new doc links
=> Replaced the doc links

pkg/hub/hubclient/hubclient.go
when the onboarded namespaces are updated to workersliceconfig , if the update fails due to conflict error , the user will not be able to delete sliceconfig! 
This PR wraps update logic under retry func
=> fix(AM-4381): add retry func while updating namespaces in workersliceconfig

controllers/slice/consts.go, controllers/slice/namespaces.go, tests/spoke/slice_netpol_test.go, tests/spoke/spoke_suite_test.go
Signed-off-by: Rahul <rahul.sawra@aveshasystems.com>
closes #38
=> feat(AM-4164): annotate allowedNS with sliceName

.github/workflows/end-to-end-test.yaml
=> testing the workflow

controllers/slice/namespaces.go, tests/emulator/hubclient/hubclient.go, tests/spoke/cluster_info_test.go, tests/spoke/node_restart_test.go, tests/spoke/slicegw_controller_test.go, tests/spoke/spoke_suite_test.go
This PR is in continuation of #55.
Integration Tests for node restart feature
=> integration tests for node restart feature

.github/workflows/go-checks.yaml
This will ensure that we can merge PRs only if the code is properly formatted using go fmt
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>
=> added go fmt checks to PR pipeline

pkg/cluster/node.go, pkg/cluster/node_reconciler.go, tests/spoke/node_restart_internalip_test.go
This PR adds support for InternalIP reqd for kind and dc clusters
=> Feature internal node ip

pkg/hub/controllers/slicegateway_controller.go
Signed-off-by: gourishkb <104021126+gourishkb@users.noreply.github.com>
=> fix(slicegw-reconcile): Fixed not returning err in reconcliation of slicegw

pkg/hub/controllers/slicegateway_controller.go
Reverts kubeslice/worker-operator#71
=> Revert "fix(slicegw-reconcile): Fixed not returning err in reconcliation of slicegw"

pkg/hub/controllers/slicegateway_controller.go
Signed-off-by: gourishkb <104021126+gourishkb@users.noreply.github.com>
=> fix(slicegw): return err not nil on failure

go.mod, go.sum, pkg/hub/hubclient/hubclient.go, tests/spoke/slice_controller_test.go, tests/spoke/spoke_suite_test.go, vendor/github.com/kubeslice/apis/pkg/controller/v1alpha1/cluster_types.go, vendor/modules.txt
* fix(AM-4841): fix for lat/long overriding and clustertype
=> fix(AM-4841): fix for geolocation (#82)

controllers/slice/namespaces.go
Isolation Enabled flag can be toggled on and off by the user. We need a mechanism to continously reconcile networkpolicies.
This PR solves that issue.
Signed-off-by: rahulsawra98 <rahul.sawra@aveshasystems.com>
=> fix(AM-4885): reconcile networkpolicies in every reconcile loop

Jenkinsfile
Signed-off-by: Venkatesh Poola <venkatesh@aveshasystems.com>
=> added unit tests parameter

config/webhook/manifests.yaml, controllers/slice/reconciler.go, main.go, pkg/webhook/deploy/webhook.go, pkg/webhook/deploy/webhook_test.go
This fix should have webhook to support non deployment workloads
=> Fix webhook to support non deployment workloads

controllers/slice/namespaces.go, controllers/slice/reconciler.go, controllers/slice/utils.go
This PR handles errors in slice cleanup logic and retries in case of errors!
=> retry slice cleanup logic

pkg/cluster/cluster.go
Signed-off-by: Bharath Horatti <bharath@aveshasystems.com>
=> fix(): Wait for subnet info in configmap

controllers/slicegateway/slicegateway.go, controllers/slicegateway/types.go, main.go, pkg/hub/hubclient/hubclient.go, pkg/monitoring/event_enums.go, pkg/monitoring/events.go, tests/emulator/hubclient/hubclient.go
Part of monitoring framework:
* Created methods and structs to raise events
* As an example, events are raised on nodeip and nodeport update on hub
=> Events monitoring package

README.md
- Rephrased
- Fixed typos
- Fixed hyperlinks
=> AM-6265: Update the worker-operator README.md file

controllers/slice/reconciler.go
Issue- Whenever the operator restarts the app pod count in exposed metrics is becoming zero. To avoid that situation we expose metric in each reconciliation loop.
Signed-off-by: YachikaRalhan <yachika.ralhan@aveshasystems.com>
=> fix(AM-6407): expose pod count in each reconciliation loop

README.md
- Rephrase the content
- Update the hyerlink
=> Update the worker-operator README.md file

controllers/slicegateway/reconciler.go, controllers/slicegateway/slicegateway.go, pkg/hub/controllers/workerslicegwrecycler/utils.go
pulling missing changes from the release branch to master
=> adding changes from release faridabad branch

pkg/hub/controllers/cluster/reconciler.go, pkg/hub/controllers/slice_controller.go
Reconcile cluster CR health status once every 120 seconds and update cluster info immediately when cluster CR is changed.
=> Feature healthstatustimer

pkg/hub/controllers/cluster/reconciler.go, pkg/hub/controllers/slice_controller.go, tests/hub/cluster_controller_test.go, tests/hub/slice_controller_test.go
increased reconcile interval, fixed ITs
=> health checks: fix reconcile interval, timeout

controllers/slice/reconciler.go, pkg/hub/controllers/slice_controller.go
* namespace was renamed to slice_namespace to avoid confusion
* use correct slice name for slice health check metrics
=> Fix labels for metrics

Jenkinsfile, pkg/hub/controllers/cluster/deregister.go, pkg/hub/controllers/cluster/deregister_unit_test.go, pkg/hub/controllers/cluster/reconciler_unit_test.go
Before creating cluster deregister Job operator will check for slice and slicegw resource.
=> fix(): race condition issue fixed when slice deletion and cluster

Jenkinsfile, pkg/hub/controllers/cluster/deregister.go, pkg/hub/controllers/cluster/deregister_unit_test.go, pkg/hub/controllers/cluster/reconciler_unit_test.go, pkg/hub/controllers/slice_controller.go, pkg/hub/controllers/slice_controller_unit_test.go
syncing `release kolkata` changes to `master`
=> feat(): sync release-kolkata to master

pkg/hub/controllers/cluster/deregister.go
Update deregister image tag to `aveshasystems/worker-installer:1.1.8`
=> fix(): update deregister job image tag

pkg/hub/controllers/cluster/cluster_controller_test.go, pkg/hub/controllers/cluster/component.go, pkg/hub/controllers/cluster/reconciler.go, pkg/hub/controllers/slice_controller.go, pkg/hub/controllers/slice_controller_unit_test.go, tests/hub/slice_controller_test.go
- Health check(both slice & cluster) based on container states instead of pod.
- gw tunnel status from gw sidecar (in slice health check)
- NodeIPs population check
- cni subnet entry check
=> health check enhancements

pkg/hub/controllers/slice_controller.go
- rectify the label used for fetching gateway objects
=> fix gateway health bug

pkg/hub/controllers/slice_controller.go
- bug fix: 
- https://avesha.atlassian.net/browse/AM-9042 (slice Gw & tunnel status not getting populated)
- https://avesha.atlassian.net/browse/AM-9119 (Wrong status for Slice Gw fix)
=> fix(): merge release-mumbai changes

pkg/hub/controllers/workerslicegwrecycler/helpers.go, pkg/hub/controllers/workerslicegwrecycler/reconciler.go, pkg/hub/controllers/workerslicegwrecycler/utils.go
This PR:
- support multiple FSM's parelly
- introduces error state
- logger fixes
=> refactor wslicegwrecycler reconciler

controllers/slicegateway/slicegateway.go
Use nodeCount by making kubernetes API call,
find count of all the nodes with kubeslice.io/node-type=gateway. 
Instead of relying on the node reconciler to update the NodeExternalIPList (and using that as the nodeCount)
=> fix(): fix gateway rebalancing

controllers/slicegateway/reconciler.go, pkg/hub/controllers/slicegateway_controller.go, tests/hub/slicegw_controller_test.go
added finalizer to slicegw for handling cluster detach scenario
=> fix(): added finalizer to slicegw (handled cluster detach scenario)

README.md
Changed the DOC hyperlinks in the ReadMe file.
=> Changed the DOC hyperlinks in the ReadMe file

.github/ISSUE_TEMPLATE/BUG.yaml, .github/ISSUE_TEMPLATE/FEATURE.yaml, .github/pull_request_template.md
Signed-off-by: Md Imran imranaec@outlook.com
=> doc(): bug format

.github/pull_request_template.md
=> fix(): Update pull_request_template checklist

config/manager/avesha-nexus.yaml
=> fix(): removed vulnerability Update avesha-nexus.yaml

pkg/hub/manager/manager.go
Fixes #335 
This issues have been addressed for all the reconciles except `SliceGwReconciler` & `ServiceImportReconciler`. Setting `client.Client` for these two, solves the issue.
```release-note
```
=> fix(): set client for slicegw & svcimport reconciler

README.md
=> Updated doc links in README.md

pkg/hub/controllers/slice_controller.go
=> fix(): add project namespace in slice label

pkg/hub/controllers/cluster/reconciler.go
=> fix(): Hotfix cni check no net

.github/workflows/scripts/start-kind.sh
Fixes: PR pipeline issue 
```release-note
```
=> fix: update KIND image version

pkg/hub/controllers/cluster/deregister.go, pkg/hub/controllers/cluster/vars.go
=> fix(): remove hardcoded worker installer image

Makefile, controllers/serviceexport/reconciler.go, controllers/vars.go
Fixes #384  
```release-note
```
=> fix: event driven reconciliation for service export

controllers/serviceexport/reconciler.go, controllers/slice/reconciler.go, pkg/webhook/pod/webhook.go
=> fix(): watch for workload changes

pkg/hub/controllers/cluster/cluster_controller_test.go, pkg/hub/controllers/cluster/component.go, pkg/hub/controllers/cluster/vars.go
The cluster health check was failing due to change in namespace & app label of nsm-admission-webhook deployment
```release-note
```
=> fix(): cluster health check

pkg/hub/controllers/serviceimport_controller.go
=> fix(AM-13847): vpc access ns creation

controllers/slice/reconciler.go
Fixes # removed duplicate reconciliation call 
```release-note
```
=> fix(): remove duplicate reconciliation calls

pkg/hub/controllers/slice_controller.go
=> fix(): copy labels from workersliceconfig to slice object

pkg/hub/controllers/slice_controller.go
=> fix(): sync labels from workerslice to slice

pkg/hub/controllers/slice_controller.go
=> fix(): sync labels from workerslice to slice (#423)

Dockerfile, Jenkinsfile
=> fix(): update golang, use TARGETOS,TARGETARCH for build
