- controllers/serviceexport/istio_serviceentry.go
- controllers/serviceexport/reconciler.go
- controllers/slice/namespaces.go
- controllers/slicegateway/reconciler.go
- tests/spoke/spoke_suite_test.go
Handled the case of nsm IP address change of slice gw due to nsm control
plane or data plane pods restarting.
For Istio, handled the case of nsm IP address change of an app pod that is
exporting a service. Updated the corresponding Istio ServiceEntry
object.
> Handle nsm IP address change of slice gw and app pods

- controllers/controller.go
- controllers/slice/namespaces.go
- pkg/networkpolicy/reconciler.go
- tests/spoke/slice_netpol_test.go
Fixes #37 
Problem: Since slice reconciler reconciles every 10 secs, the reconciler would call apiserver to netpol (even though it is not updated) .
Fix: slice reconciler would only install/update netpol when application/allowed namespaces are updated.
User edits to netpol would be handled by networkpolicy reconciler
> Feature enhance netpol

- go.mod
- go.sum
- pkg/hub/hubclient/hubclient.go
- tests/spoke/slice_controller_test.go
- tests/spoke/spoke_suite_test.go
- vendor/github.com/kubeslice/apis/pkg/controller/v1alpha1/cluster_types.go
- vendor/modules.txt
This PR fixes the overriding geolocation lat and long data in cluster CR and only sends geolocation data in case in aws,azure and gcp.
also fixes the test cases failing in master
> fix(AM-4841): fix for geolocation

- controllers/slicegateway/reconciler.go
While refactoring changes for sonarqube warnings , sliceGwNodePort was passed to a different function but its value was never returned back hence the value was being set as 0.
This PR fixes this issue
> fix(AM-4902): fix nodePort value populating as 0

- api/v1beta1/groupversion_info.go
- controllers/slice/app_pod.go
- controllers/slice/namespaces.go
- controllers/slice/slicerouter.go
- controllers/slicegateway/reconciler.go
- controllers/slicegateway/slicegateway.go
- main.go
- pkg/cluster/cluster.go
- pkg/logger/logger.go
- pkg/manifest/egress.go
- pkg/manifest/ingress.go
- pkg/metrics/metrics.go
- pkg/webhook/pod/pod_suite_test.go
- pkg/webhook/pod/webhook.go
- pkg/webhook/pod/webhook_test.go
- pkg/webhook/pod/webhook_utils.go
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>
Recently the webhook was modified to mutate pods instead of deployments. The package name and variable names were still using the word "deploy". This PR fixes this to improve code readability.
note: the spacing changes are from `go fmt`
> Rename deploy webhook package name to pod

- controllers/controller.go
- controllers/serviceexport/istio_serviceentry.go
- main.go
- pkg/cluster/node.go
- pkg/hub/hubclient/hubclient.go
- pkg/hub/manager/manager.go
- pkg/logger/logger.go
- pkg/manifest/file.go
- pkg/metrics/metrics.go
- pkg/monitoring/monitoring.go
- pkg/webhook/pod/webhook.go
- tests/spoke/slice_controller_test.go
To introduce standard logging fields and conventions, we need to fix the following limitations with the current codebase
* `go-logr` logr.logger interface doesn't support log levels (they use verbose level number instead). 
* Top level fields (ts, msg etc) are not as per google structured logging standard. This makes it difficult to view the logs in google console. https://cloud.google.com/logging/docs/structured-logging
To fix this, this PR introduces the following changes (more PRs to follow)
* Add standard logging fields `namespace` and `sliceCluster`
* Change log field names
* level -> severity
* msg -> message
* ts -> timestamp 
* Expose SugaredLogger from zap to use warn and debug levels directly
* Rename `NewLogger` to `NewWrappedLogger` and expose SugaredLogger under `NewLogger`
* …
> Introduce standard log fields and expose zap.SugaredLogger

- pkg/featureflag/featureflag.go
- pkg/featureflag/featureflag_test.go
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>
A simple implementation of feature flags using env variables.
usage:
```go
import (
"github.com/kubeslice/worker-operator/pkg/featureflag"
)
...
if featureflag.IsEnabled("nodeaffinity") {
// your code
}
```
> Add support for feature flags

- controllers/slice/namespaces.go
- tests/spoke/namespace_sameness_test.go
- Creating a namespace if that particular namespace is not available in the any cluster which is part of the slice. 
- Prior to this edit, operator reconciler used to throw error, but waited for namespace to be created by user.
> feat(AM-5509): Namespace sameness on a slice 

- controllers/serviceexport/reconciler.go
- controllers/serviceexport/serviceexport.go
- controllers/serviceexport/utils.go
- tests/spoke/namespace_controller_test.go
- tests/spoke/service_discovery_test.go
- tests/spoke/service_import_test.go
- tests/spoke/slice_controller_test.go
- tests/spoke/slice_netpol_test.go
- tests/spoke/slicegw_controller_test.go
* Avoid onboarding serviceexport when namespace is not part of slice
* Avoid onboarding pods which are not part of slice
* Avoid onboarding serviceexport when slice is not present
* Fix flaky tests which were causing checks to fail in this PR
> Serviceexport fixes

- pkg/hub/controllers/slice_controller.go
- pkg/hub/controllers/slice_controller_unit_test.go
- tests/files/crd/spoke.kubeslice.io_spokesliceconfigs.yaml
- tests/hub/hub_suite_test.go
- tests/hub/slice_controller_test.go
Slice Health status checks the status of the following components : dns, slicerouter, slicegateway, ingress, egress and updates the overall slicehealthstatus with either a _normal_ or _warning_ state. 
The state can be observed on the controller cluster by `kubectl get workersliceconfig <slicename-clustername> -o yaml`
> feat(): Slice Health Status

- pkg/hub/controllers/cluster/reconciler.go
- pkg/hub/controllers/slice_controller.go
Use retry on conflict for updating slice/cluster health status to avoid update errors.
> fix(): fix health status update conflicts

- controllers/slice/reconciler.go
- pkg/hub/controllers/cluster/reconciler.go
- pkg/hub/controllers/slice_controller.go
- pkg/hub/controllers/slice_controller_unit_test.go
- tests/hub/slice_controller_test.go
- tests/spoke/node_restart_test.go
- tests/spoke/slicegw_controller_test.go
When multiple slices are deployed,
failure of one slice's components is reflected
in all the other sliceHealthStatus
Fix: added sliceName label to filter out
individual slice specific components
> fix(): Fixed interference of sliceHealthStatus

- pkg/hub/controllers/cluster/reconciler.go
In cluster reconciler, we were not requeueing after updating the CR, which caused conflicts when updating health check. This is not really a big issue, since health check is updated in the next iteration correctly. However a fix is added to avoid unnecessary warnings in the logs
> fix retry conflicts on health check update

- pkg/hub/controllers/slice_controller.go
- pkg/hub/controllers/slice_controller_unit_test.go
- tests/hub/slice_controller_test.go
For a single cluster, sliceGW pods are missing.
We need to handle component health status for two cases 1. single cluster 2. multiple cluster
case 1: we check if sliceGW deployment is present, expected no slicegw deployments hence, mark healthystate
case 2: we check if sliceGW deployment is present, expected 1 slicegw deployment, hence, list all pods and check if all are in Running state else mark as unhealthyState
> fix(): fixed slicegw health status for single cluster

- pkg/hub/controllers/cluster/reconciler.go
* If cluster.spec.nodeIPs contains empty string []string{""} then worker operator is not able to update the nodeIPs.
* removed the check where we are checking if the `ClusterHealth == nil` this condition will be always true after the first reconcilation due to which in case there is a nodeIP change detected reconciler will never call the `updateClusterInfo` function.
> fix(): nodeip update while empty string

- pkg/hub/controllers/cluster/reconciler.go
- pkg/hub/controllers/slice_controller.go
- pkg/hub/controllers/slice_controller_unit_test.go
- tests/hub/slice_controller_test.go
For a single cluster, sliceGW pods are missing.
We need to handle component health status for two cases 1. single cluster 2. multiple cluster
case 1: we check if sliceGW deployment is present, expected no slicegw deployments hence, mark healthystate
case 2: we check if sliceGW deployment is present, expected 1 slicegw deployment, hence, list all pods and check if all are in Running state else mark as unhealthyState
> fix(): slicegw health status for single cluster

- controllers/slicegateway/slicegateway.go
- If there is a change in "sliceGatewayRemoteNodeIps", we update the endpoint addresses.
- When all the node IPs are distinct, we restart the gateway pods to refresh the connections.
> fix(): restart gateway pod when distinct node ips

- pkg/hub/controllers/slicegateway_controller.go
Removing the logic to raise events based on controller CRDs. It doesn't make sense to be in worker operator.
> Fix: operator trying to raise events for controller CRDs

- controllers/serviceexport/serviceexport.go
- tests/files/crd/networking.kubeslice.io_serviceexports.yaml
- tests/spoke/service_discovery_test.go
- tests/spoke/spoke_suite_test.go
Bug fix for https://avesha.atlassian.net/browse/AM-7487
Serviceexport reconciliation was failing when new items were added to the list of aliases.
> fix(): Fixed alias update in service export

- controllers/serviceexport/reconciler.go
- controllers/serviceimport/reconciler.go
- main.go
- pkg/hub/controllers/cluster/reconciler.go
- pkg/hub/manager/manager.go
- tests/hub/hub_suite_test.go
- tests/hub/slice_controller_test.go
- tests/spoke/service_import_test.go
- tests/spoke/spoke_suite_test.go
- tests/utils/metrics.go
Adds a new metric `kubeslice_serviceimport_endpoints` in serviceimport reconciler with corresponding UTs. This is a guage which shows number of active endpoints for each serviceimport in a slice.
Also made some minor label changes to existing metrics
Please delete options that are not relevant.
> Metrics for serviceimport endpoints

- pkg/hub/controllers/slice_controller.go
- tests/hub/hub_suite_test.go
- tests/hub/slice_controller_test.go
This PR adds the slice health related metrics.
1. kubeslice_slice_up : gauge set to 1 when slice health is Normal state and set to 0 when slice health is in warning state
2. kubeslice_slice_component_up : gauge set to 1 when slice component is in Normal state and set to 0 when slice component is in Error state
Added integration tests to cover both the states of the above metrics
> Add slice health metrics

- pkg/hub/controllers/cluster/deregister.go
- pkg/hub/controllers/cluster/deregister_unit_test.go
- pkg/hub/controllers/cluster/reconciler_unit_test.go
The race condition issue that occurs when deleting slices and deregistering clusters quickly has been resolved
> fix(): race condition issue fixed btw slice detach and cluster deregister

- pkg/hub/controllers/slice_controller.go
- pkg/hub/controllers/slice_controller_unit_test.go
slice name of the workersliceConfig is currently used, this change uses the correct slice name from SliceConfig, which is part of the spec for WorkerSliceConfig
> fix(): use correct slicename

- controllers/serviceexport/reconciler.go
- tests/spoke/service_discovery_test.go
Adds a new metric `kubeclice_serviceexport_aliases` guage to show the number of aliases configured per serviceexport.
Also added corresponding test cases.
> added metric for service_export aliases

- controllers/serviceimport/istio_serviceentry.go
Changed the istio serviceentry resolution to static from dns when setting up the istio egress gw. There is a problem with dns resolution when the istio-proxy is run in the router mode wherein the resolution of hostnames fails intermittently and in some cases it remains in the failed state for a very long time. This issue is not seen with istio-proxy running in sidecar mode.
We use static resolution for istio ingress gw, following the same practice for egress gw as well.
> fix(): Changed istio serviceentry resolution to static

- controllers/serviceimport/istio_serviceentry.go
Backing out static resolution of Istio ServiceEntries. It was added as a workaround for a dns resolution bug in istio. There are a few changes in NSM that will take care of the istio bug.
> fix(): Back out static resolution in ServiceEntries

- pkg/webhook/pod/webhook.go
This PR fixes nil pointer dereference issues if label field for object is empty.
Issue was observed with the following error message: 
Error from server (InternalError): error when creating "/private/var/folders/79/1qpw4sq56h93prvrqhmj6p7m0000gn/T/1ae182ebc8f383cb5affcef7da4a38fa/resource.yaml": Internal error occurred: failed calling webhook "webhook.kubeslice.io": failed to call webhook: Post "[https://kubeslice-webhook-service.kubeslice-system.svc:443/mutate-webhook?timeout=10s](https://kubeslice-webhook-service.kubeslice-system.svc/mutate-webhook?timeout=10s)": EOF 
This was due to trying to de-reference a nil object in the webhook code. 
Fixes issues with pod,deployment,statefulset and daemonset objects having no labels (i.e nil Label object)
> fix(): Initialize labels field as an empty map

- pkg/hub/controllers/cluster/reconciler.go
> fix(): added support for linode clusters

- controllers/slice/slice_gw_edge.go
Fixes # 
The LB is getting stuck into "pending" state on aws when protocol is TCP
https://avesha.atlassian.net/browse/AM-12246
```release-note
```
> fix(AM-12246): apply EKS specific annotations for NLB creation

- main.go
- pkg/webhook/pod/webhook.go
Assign the `decoder` field directly during the initialization of `WebhookServer` in the main package.
Remove the `InjectDecoder` method on `WebhookServer` as the `controller-runtime` package no longer allows injections.
Fixes #338
This is an error with initialization and cannot be tested as a feature.
Steps to test this manually are in #338.
```release-note
```
> fix(WebhookServer): Fix webhook EOF error when creating resources (#338)

- config/rbac/role.yaml
- controllers/slicegateway/pod_disruption_budget.go
- controllers/slicegateway/reconciler.go
- controllers/slicegateway/slicegateway.go
- tests/spoke/slicegw_controller_test.go
A `PodDisruptionBedget` is required that matches the slice gateway pods, and to specify a minimum availability of 1 pod in case of disruptions.
The `SliceGwReconciler` handles the lifecycle of this `PodDisruptionBudget` object.
Added RBAC permissions for `SliceGwReconciler` to maintain `PodDisruptionBudget`.
Fixes #308
- Since the change is user facing, i.e., the PDB is one extra resource that will be visible to users, I think it is better to a add some explanation in the documentation.
- Updated the RBAC permissions for CRUD on PodDisruptionBudget objects. However, a PR for the same has to be created once this is approved.
- Added 3 subtest cases under spoke tests.
```release-note
```
1. Deploy the whole setup controller and 2 workers. Check if there are slice gateway pods similar to …
> feat(SliceGwReconciler): Add `PodDisruptionBudget` logic to `SliceGwReconciler` (#308)

- controllers/slice/reconciler.go
- controllers/slice/utils.go
- pkg/hub/controllers/cluster/reconciler.go
- tests/spoke/slice_controller_test.go
Fixes #AM-13396 
- resolved app pod & kubeslice dns pod not found error
- clean up cni subnets from cluster object when kubeslice networking is disabled
```release-note
```
> fix(AM-13396): fix app & dns pods related errors

- controllers/slicegateway/slicegateway.go
- controllers/slicegateway/utils.go
- tests/spoke/slicegw_controller_test.go
Fixes #309 
Tested it manually using two single node kind clusters.
```release-note
```
> fix: reconcile gateway client's node port

- config/webhook/manifests.yaml
- controllers/slice/reconciler.go
- main.go
- pkg/webhook/pod/webhook.go
- pkg/webhook/pod/webhook_test.go
- pkg/webhook/pod/webhook_utils.go
The validating webhook will validate the ServiceExport object and admission of ServiceExport objects with conflicting alias names will be rejected.
Fixes #315 
```release-note
```
> fix(ServiceExport): Reject Conflicting Alias Names for ServiceExport object (#315)

- pkg/namespace/controllers/reconciler.go
- pkg/utils/constants.go
This provides a configurable way to provide a list of namespaces to be excluded in namespace reconcilers. It can be passed through an environment variable. If not provided a default list would be used.
Fixes # 
```release-note
```
> fix(): configurable ns exclusion list

- api/v1beta1/slicegateway_types.go
- config/crd/bases/networking.kubeslice.io_slicegateways.yaml
- controllers/slicegateway/slicegateway.go
- controllers/slicegateway/utils.go
- pkg/gwsidecar/gwsidecar.go
The gw tunnel status is recorded in the slicegateway CR status field. There are a number of fields like the interface name, rx and tx rates, latency and pkt loss in the status field but not all of them are getting filled. This is occurring because of an incorrect type conversion between gwpod.TunnelStatus and gwsidecar.TunnelStatus. The former struct is what is written to the status field of the CR and the latter is the struct that is filled by the grpc messaging between the operator and the gw sidecar. 
The code changes in this PR address the above issue. It also adds additional info in the status field of the CR like the remote port number an instance of gw client is connecting to, and the tunnel state in string format for ease of debugging. The code also contains a couple of fixes for …
> fix(): Fixed tunnel status reporting in the slicegw CR

- Dockerfile
- controllers/slicegateway/slicegateway.go
- go.mod
- test.Dockerfile
Fixes: update if gateway sidecar image has been changed in worker-operator env vars
```release-note
```
> fix(): update gw deploy if gateway sidecar image changed

- controllers/slicegateway/slicegateway.go
Fixes #
update gateway deployment if gateway sidecar image pull policy is changed in kubeslice-operator's env vars
```release-note
```
> fix(): reconcile gateway sidecar image pull policy
